### ISSUE TITLE
save_and_scrapeGS

### ISSUE THREAD

**Issue by tomryjo** [nealhaddaway/GSscraper#5]
Hi Neal, thank you very much for your hard work. I got an error when trying to run the command save_and_scrapeGS.  

Here is the code:
and_terms <- c("green","logistics")
naive_results <- GSscraper::save_and_scrapeGS(and_terms = and_terms, pages = 10)

and this is the error:
Error in data.frame(values = unlist(unname(x)), ind, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 105, 100

I really appreciate your help.

Very best,

Nguyen

**Comment by nealhaddaway** [comment]
I've finally rewritten the commands to reflect underlying base HTML code changes on Google Scholar. The shiny app is up-to-date, but I'll work on the core functions in the /R folder and repackage and send to CRAN ASAP. So sorry for the delay!
