### ISSUE TITLE
License

### ISSUE THREAD

**Issue by edalfon** [nealhaddaway/GSscraper#6]
Hi Neal,

Straight to the point: would you mind adding a license for GSscraper?, ideally, a permissive one such as MIT?

We've found GSscraper is a great addition to our workflows to automate the process of keeping systematic reviews up to date. And although it is a great starting point, there is room for improvement. But currently the project has no license at all, which means that ["no one may reproduce, distribute, or create derivative works from your work"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

So yeah, a permissive license would be great. Hope you can do it.

Best,

**Comment by nealhaddaway** [comment]
Hey,
I can add a license file but is has a GPL-3 license (check the description).
Thanks

Sent from my iPhone

On 24 Oct 2021, at 09:20, edalfon ***@***.***> wrote:

﻿

Hi Neal,

Straight to the point: would you mind adding a license for GSscraper?, ideally, a permissive one such as MIT?

We've found GSscraper is a great addition to our workflows to automate the process of keeping systematic reviews up to date. And although it is a great starting point, there is room for improvement. But currently the project has no license at all, which means that "no one may reproduce, distribute, or create derivative works from your work"<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository>.

So yeah, a permissive license would be great. Hope you can do it.

Best,

**Comment by edalfon** [comment]
Cool, that'd be great!
