### ISSUE TITLE
Error on pages retrieved

### ISSUE THREAD

**Issue by copariuc** [nealhaddaway/GSscraper#7]
Hi.
info <- save_and_scrapeGS(and_terms = search.phrase,
                          language = "en", year_from = "", year_to = "",
                          pages = 2, path = "Pages/", pause = 5,
                          backoff = F)
Initially worked, after a number of requests the pages contains only the message `Please show you're not a robot` and `Localhost is not in the list of supported domains for this site key.` I guess is a reCapthca problem. Can you help me? Thank you

**Comment by nealhaddaway** [comment]
I'm afraid this is blocking from Google Scholar - currently there is no VPN built in, so this is a risk if Google thinks use constitutes a breach of Terms. Sorry!
________________________________
From: Cristian Opariuc-Dan ***@***.***>
Sent: 05 January 2022 14:42
To: nealhaddaway/GSscraper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nealhaddaway/GSscraper] Error on pages retrieved (Issue #7)


Hi.
info <- save_and_scrapeGS(and_terms = search.phrase,
language = "en", year_from = "", year_to = "",
pages = 2, path = "Pages/", pause = 5,
backoff = F)
Initially worked, after a number of requests the pages contains only the message Please show you're not a robot and Localhost is not in the list of supported domains for this site key. I guess is a reCapthca problem. Can you help me? Thank you
